<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>latest</LangVersion>
    <Prefer32Bit>false</Prefer32Bit>
    <RootNamespace>EmojiWindowEcommerceWorkspaceSketchDemo</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <ApplicationIcon>favicon.ico</ApplicationIcon>
    <StartupObject>EmojiWindowEcommerceWorkspaceSketchDemo.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="obj\**\*.cs" />
    <Compile Remove="bin\**\*.cs" />
    <Reference Include="FBroSharpInterface">
      <HintPath>$(NuGetPackageRoot)fbrosharp.common\5.31.32\lib\FBroSharpInterface.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="FBroSharpLib">
      <HintPath>$(NuGetPackageRoot)fbrosharp.common\5.31.32\lib\x64\FBroSharpLib.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <None Include="favicon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="qrcode_523446917.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="emoji_window.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FBroSharp.Common" Version="5.31.32" />
    <PackageReference Include="FBroSharp.x64" Version="5.31.32" />
  </ItemGroup>

  <Target Name="CopyFbroSharpRuntimeFiles" AfterTargets="Build">
    <CallTarget Targets="CefRedist64CopyResources" />
  </Target>
</Project>
